---
# Setup installation repositories

- name: import repository key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0xcbcb082a1bb943db

- name: add apt repository
  apt_repository: repo="deb http://mirror.jmu.edu/pub/mariadb/repo/5.5/{{ ansible_distribution|lower() }} {{ ansible_distribution_release }} main"
    state=present update_cache=yes
